name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  create_github_release:
    name: Create a release object in Github
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Roang-zero1/github-create-release-action@v2.3.0
      with:
        version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$
        prerelease_regex:  ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+-beta.*$
        update_existing: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  packager_release:
    needs:
      - create_github_release
    name: Package and Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bigwigs packager
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_TOKEN }}
        with:
          args: "-o -u -m .pkgmeta -S"
      - name: Get name of zip file
        run: echo "artifact=`readlink -f .release/*.zip`" >> $GITHUB_ENV
      - name: Upload artifact to github
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: ${{ env.artifact }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}