name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  packager_release:
    name: Package and Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bigwigs packager
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_TOKEN }}
        with:
          args: "-o -u -m .pkgmeta -S"